version: "3.8"

services:
  flask-ml:
    build: .
    container_name: flask-ml
    restart: unless-stopped

    networks:
      - web

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.flask.rule=Host(`flask.kuyen.online`)"
      - "traefik.http.routers.flask.entrypoints=websecure"
      - "traefik.http.routers.flask.tls.certresolver=letsencrypt"
      - "traefik.http.services.flask.loadbalancer.server.port=5000"

networks:
  web:
    external: true