name: Build Image (Kaniko)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    container:
      image: gcr.io/kaniko-project/executor:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Auth
        run: |
          mkdir -p /kaniko/.docker
          cat <<EOF > /kaniko/.docker/config.json
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "username": "${{ secrets.DOCKER_USERNAME }}",
                "password": "${{ secrets.DOCKER_PASSWORD }}"
              }
            }
          }
          EOF

      - name: Build & Push Image
        run: |
          /kaniko/executor \
            --dockerfile=Dockerfile \
            --context=. \
            --destination=dans9881/flask-ml-app:latest \
            --verbosity=info